### ISSUE TITLE
Use categories as a scoring function

### ISSUE THREAD

**Issue by hkrishna** [pelias/api#105]
Each point has a field called ```category``` that contains some valuable information, it would be nice to use this information in the scoring algorithm.

We could have a file ```weighted_categories.yml``` where we can define what weight each tag value corresponds to.

```yml
   airport: 12
   railway: 10
   restaurant: 8
   tourism: 11
   poi:landmark: 10
   ...
```
This should be a query time boosting easily do-able by just adding a [script](http://github.com/pelias/scripts) and using it in the API sorting logic. 

Related to pelias/openstreetmap#33 and pelias/pelias#50
